apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: core
  description: Team CORE
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-core@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
    parent: backstage
  children: [kubernaughts]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: kubernaughts
  description: Kubernaughts
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: kubernaughts@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: core
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: peter
spec:
  profile:
    displayName: Peter
    email: peter@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [kubernaughts]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: luke
spec:
  profile:
    displayName: Luke
    email: luke@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [kubernaughts]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [core]